### ISSUE TITLE
Allow users to draft text

### ISSUE THREAD

**Issue by marklocklear** [marklocklear/twitter-splitter#3]
https://getchirrapp.com/ uses local storage to "save" text. Note if you paste text in their app, you can leave the page, then come back and the state is saved.

**Comment by johndavenport71** [comment]
I implemented local storage usage but it doesn't output anything when the page loads. I pushed my changes up with a development branch for you to check out.

**Comment by marklocklear** [comment]
Looks good. https://github.com/marklocklear/twitter-splitter/pull/7
